Feat/sent video-and-chat-group
saigontechnology/rn-firebase-chat pull request #12
Opened 2023-12-27 06:52 UTC by ZanBin

<img width="1029" alt="Screenshot 2023-12-27 at 13 36 23" src="https://github.com/saigontechnology/rn-firebase-chat/assets/150883191/76abb874-3c9d-43ef-94a5-a64ed174a271">

2023-12-27 17:05 UTC, baonguyenhsts requested changes

2023-12-28 03:07 UTC, loc-nguyenthien requested changes

2023-12-28 03:07 UTC, loc-nguyenthien commented on src/Utilities/ultis.ts
> +};
Too complicated, I suggest we write it like this
```
export const haveSameContents = <T>(a: T[], b: T[]): boolean => {
    return a.length === b.length && a.every(item => b.includes(item))
};
```

2023-12-28 09:32 UTC, loido commented on example/src/Chat/Component/CustomInputMessage.tsx
>          icon={require('../../Assets/image.png')}
can you please create a constant for those URL icons?

2023-12-28 09:32 UTC, loido commented on example/src/Chat/Component/CustomInputMessage.tsx
> +        icon={require('../../Assets/upload_file.png')}
can you please create a constant for those URL icons?

2023-12-28 09:32 UTC, loido commented on src/Chat/ChatProvider.tsx
> +            file['type'] = MEDIA_FILE_TYPE.image
can you update `file['type']` to `file.type`?

2023-12-28 09:32 UTC, loido commented on src/Chat/ChatProvider.tsx
> +            file['type'] = MEDIA_FILE_TYPE.video
can you update file['type'] to file.type?

2023-12-28 09:32 UTC, loido commented on src/Chat/ChatProvider.tsx
> +            file['type'] = MEDIA_FILE_TYPE.file
can you update file['type'] to file.type?

2023-12-28 09:32 UTC, loido commented on src/Chat/ChatProvider.tsx
> +          setLoadEarlier(false);
`setLoadEarlier(false);` it should inside finally. Because it always true if getMessageHistory is error

2023-12-28 10:08 UTC, baonguyenhsts requested changes

2023-12-28 10:08 UTC, baonguyenhsts commented on example/src/Chat/ChatScreen.tsx
> +      if (!imageUrl) {
Remove this condition because it will never happen

2023-12-28 10:08 UTC, baonguyenhsts commented on example/src/Chat/Component/CustomInputMessage.tsx
>  import * as ImagePicker from 'react-native-image-picker';
```suggestion
import ImagePicker from 'react-native-image-picker';
```

2023-12-28 10:08 UTC, baonguyenhsts commented on example/src/Chat/Component/CustomInputMessage.tsx
>            marginHorizontal: 12,
no-inline-styles

2023-12-28 11:49 UTC, closed without merging