Feat/sent image
saigontechnology/rn-firebase-chat pull request #13
Opened 2023-12-28 12:07 UTC by ZanBin

2023-12-29 02:59 UTC, loc-nguyenthien requested changes

2023-12-29 02:59 UTC, loc-nguyenthien commented on example/src/Chat/Component/CustomInputMessage.tsx
> +      try {
double `try-catch`?

2023-12-29 04:11 UTC, baonguyenhsts requested changes

2023-12-29 04:11 UTC, baonguyenhsts commented on src/Chat/ChatProvider.tsx
> -      let file;
why do you remove this line?

2023-12-29 04:11 UTC, baonguyenhsts commented on src/Chat/ChatProvider.tsx
> +      };
What happen if the file is
```
{
        imageUrl: undefined
        extension: undefined,
        type: undefined
      }
```

2023-12-29 04:11 UTC, baonguyenhsts commented on src/Services/Firestore/firestore.ts
> +  constructor() { }
prettier config

2023-12-29 04:11 UTC, baonguyenhsts commented on src/Services/Firestore/firestore.ts
> +        return;
Should log error if the conversationId doesn't exist

2023-12-29 04:11 UTC, baonguyenhsts commented on src/Services/Firestore/firestore.ts
> +        status: 'pending',
use MESSAGE_STATUS constant

2023-12-29 04:11 UTC, baonguyenhsts commented on src/Services/Firestore/firestore.ts
> +                status: 'sent',
use MESSAGE_STATUS constant

2023-12-29 04:11 UTC, baonguyenhsts commented on src/Services/Firestore/firestore.ts
> +            .then((imageUrl) => {
```suggestion
            .then((downloadURL) => {
```

2023-12-29 04:11 UTC, baonguyenhsts commented on src/Services/Firestore/firestore.ts
> +                    status: 'sent',
use MESSAGE_STATUS constant

2023-12-29 04:11 UTC, baonguyenhsts commented on src/Services/Firestore/firestore.ts
> +      .then((e) => {
Why do you use `async/await` with `then`?

2024-06-14 03:25 UTC, hoangSTS commented on example/src/Chat/Component/CustomInputMessage.tsx
> +const byteToMB = 1048576;
what does it mean and used for?

2024-06-14 03:26 UTC, closed without merging

2024-06-14 03:29 UTC, hoangSTS commented on example/src/Chat/Component/CustomInputMessage.tsx
> +            onSend?.({imageUrl: uri, extension: type, type: 'image'}, true);
replace 'image' by IMAGE_TYPE above