feat: can send image and video on chat firebase
saigontechnology/rn-firebase-chat pull request #14
Opened 2024-01-05 04:50 UTC by huydosgtech

2024-01-05 06:45 UTC, ledutu2 commented on example/src/Chat/ChatScreen.tsx
> +        }}
I think you need to create a new function instead of an inline function.

2024-01-05 06:45 UTC, ledutu2 commented on example/src/Chat/ChatScreen.tsx
> +        wrapperStyle={{
Could you remove the inline style?

2024-01-05 06:45 UTC, ledutu2 commented on example/src/Utilities/utils.ts
> +  const imageExtension = ['jpg', 'jpeg', 'png'];
how about if the URL includes "png" in the middle?
You can refer to this solution:
`
function isImageUrl(url) {
  const pattern = /(http(s?):)([/|.|\w|\s|-])*\.(?:jpg|gif|png|jpeg|bmp|webp|svg)$/;
  return pattern.test(url);
}
`

2024-01-12 07:56 UTC, hoangSTS approved these changes

2024-01-15 08:12 UTC, honghoangsts requested changes

2024-01-15 10:19 UTC, baonguyenhsts requested changes

2024-01-15 10:19 UTC, baonguyenhsts commented on src/interfaces/message.ts
> +  type?: 'file' | 'image' | 'video';
use MEDIA_FILE_TYPE from the constants

2024-01-15 10:19 UTC, baonguyenhsts commented on src/Services/Firestore/firestore.ts
> +          .then((imageUrl) => {
use await instead of then

2024-01-15 10:19 UTC, baonguyenhsts commented on src/Services/Firestore/firestore.ts
> +              .then((snapShot) => {
use await instead of then

2024-01-15 10:19 UTC, baonguyenhsts commented on src/Services/Firestore/firestore.ts
> +          .then((snapShot) => {
use await instead of then

2024-01-15 10:19 UTC, baonguyenhsts commented on src/Chat/ChatProvider.tsx
> +          type: '',
```suggestion
          type: MEDIA_FILE_TYPE[messageType],
```

2024-01-15 10:19 UTC, baonguyenhsts commented on src/Chat/ChatProvider.tsx
> +          type: '',
remove the switch case

2024-01-15 10:19 UTC, baonguyenhsts commented on example/src/Chat/CreateUser.tsx
> +      {enableChatGroup &&
group `enableChatGroup` logic

2024-01-15 10:19 UTC, baonguyenhsts commented on example/src/Chat/CreateUser.tsx
> +    if (!isAllMemberExist) {
use DP Guard Clause

2024-01-17 13:59 UTC, huydosgtech commented on example/src/Chat/Component/CustomInputMessage.tsx
> +          if (assets && assets?.length > 0) {
when use **if (assets?.length > 0)** `get issue 'assets.length' is possibly 'undefined'.ts(18048)`. Can we keep it?

2024-01-17 15:16 UTC, huydosgtech commented on example/src/Chat/CreateUser.tsx
> +    if (!isAllMemberExist) {
updated. Please check again

2024-01-17 15:16 UTC, huydosgtech commented on example/src/Chat/CreateUser.tsx
> +      {enableChatGroup &&
updated. Please check again

2024-01-17 15:16 UTC, huydosgtech commented on src/Chat/ChatProvider.tsx
> +          type: '',
updated. Please check again

2024-01-17 15:16 UTC, huydosgtech commented on src/Services/Firestore/firestore.ts
> +          .then((snapShot) => {
updated. Please check again

2024-01-17 15:16 UTC, huydosgtech commented on src/interfaces/message.ts
> +  type?: 'file' | 'image' | 'video';
updated. Please check again

2024-01-17 15:16 UTC, huydosgtech commented on example/src/Chat/Component/CustomInputMessage.tsx
> +          mediaType: 'mixed',
updated. Please check again

2024-01-17 15:16 UTC, huydosgtech commented on example/src/Chat/ChatScreen.tsx
> +  image: {width: 150, height: 150},
updated. Please check again

2024-01-19 03:36 UTC, baonguyenhsts requested changes

2024-01-19 03:36 UTC, baonguyenhsts commented on example/src/Chat/Component/CustomInputMessage.tsx
> +      const options = {
move this options outside the component

2024-01-19 03:36 UTC, baonguyenhsts commented on example/src/Chat/Component/CustomInputMessage.tsx
> +        } else if (type?.includes(MEDIA_FILE_TYPE.image)) {
remove
```suggestion
        } 
        if (type?.includes(MEDIA_FILE_TYPE.image)) {
```

2024-01-19 03:36 UTC, baonguyenhsts commented on src/Chat/ChatProvider.tsx
> +      <View ref={ref} style={[styles.container, style]}>
Why do we need this `ref`?

2024-01-19 03:36 UTC, baonguyenhsts commented on src/Services/Firestore/firestore.ts
> +          status: 'sent',
use MESSAGE_STATUS constants

2024-01-24 14:25 UTC, huydosgtech commented on example/src/Chat/Component/CustomInputMessage.tsx
> +          if (assets && assets?.length > 0) {
this ok but only check not null/undefined

2024-01-24 15:09 UTC, huydosgtech commented on src/Chat/ChatProvider.tsx
> +      <View ref={ref} style={[styles.container, style]}>
If not will show warning in console

2024-01-24 15:10 UTC, huydosgtech commented on src/Services/Firestore/firestore.ts
> +          status: 'sent',
updated. Please check again

2024-01-24 15:10 UTC, huydosgtech commented on example/src/Chat/Component/CustomInputMessage.tsx
> +      const options = {
updated. Please check again

2024-01-24 15:10 UTC, huydosgtech commented on src/Services/Firestore/firestore.ts
> +          status: 'sent',
updated. Please check again

2024-06-14 07:40 UTC, closed without merging