Feat/custom chat
saigontechnology/rn-firebase-chat pull request #20
Opened 2024-05-27 04:52 UTC by huydosgtech

2024-05-27 05:04 UTC, huydosgtech commented
video demo: 

https://github.com/saigontechnology/rn-firebase-chat/assets/105196859/a9839984-04de-458a-b9de-8c0f32ff0f3e

2024-05-28 03:24 UTC, honghoangsts requested changes

2024-05-31 02:40 UTC, huydosgtech commented on example/src/navigation/AppNavigator.tsx
> +  const navigationRef = useRef<any>();
yes, I updated. Please help me check it

2024-06-03 14:58 UTC, honghoangsts commented on src/chat/ChatProvider.tsx
> +        dispatch(setConversation(data));
`updateConversation`

2024-06-03 14:59 UTC, honghoangsts commented on src/chat/components/InputToolbar.tsx
> +    <View>
Do we need this `View`

2024-06-03 15:00 UTC, honghoangsts commented on src/interfaces/chat.ts
> +  memberId: string;
why we need add `memberId` to `IUserInfo`

2024-08-02 02:20 UTC, closed without merging