feat: [Fc-2] Show in comming message
saigontechnology/rn-firebase-chat pull request #22
Opened 2024-06-05 08:21 UTC by huydosgtech

2024-06-05 08:25 UTC, huydosgtech commented
Video demo: 

https://github.com/saigontechnology/rn-firebase-chat/assets/105196859/ccb2ffa5-3c39-4c85-9e63-d82ff1782c5d


https://github.com/saigontechnology/rn-firebase-chat/assets/105196859/a9a05a7e-81a2-4d75-8e92-4c505ac53533

2024-06-05 14:14 UTC, honghoangsts requested changes

2024-06-07 04:18 UTC, huydosgtech commented on src/reducer/action.ts
> +  UPDATE_USER_CONVERSATION = 'UPDATE_USER_CONVERSATION',
yes, I updated it. Please check again

2024-06-07 04:18 UTC, huydosgtech commented on src/chat/ChatScreen.tsx
> +          setMessagesList(mergeMessageList);
yes, I updated it. Please check again

2024-06-07 04:18 UTC, huydosgtech commented on src/reducer/action.ts
> +export const updateUserConversation = (payload: ConversationProps) => ({
yes, I updated it. Please check again

2024-06-08 14:36 UTC, huydosgtech commented on src/reducer/chat.ts
> +      const newListMessage = (state.listConversation || [])
I updated, please help me check it. Thank you

https://github.com/saigontechnology/rn-firebase-chat/assets/105196859/0aa65834-6a54-4058-a998-3f2db82af622

2024-06-11 03:22 UTC, honghoangsts commented on src/chat/ChatScreen.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
remove eslint-disable-next-line react-hooks/exhaustive-deps

2024-06-11 04:11 UTC, huydosgtech commented on src/chat/ChatScreen.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
I updated

2024-06-12 01:45 UTC, merged