fix: issue receive message in the past make duplicate
saigontechnology/rn-firebase-chat pull request #28
Opened 2024-06-13 16:43 UTC by huydosgtech

2024-06-14 06:53 UTC, loc-nguyenthien requested changes

2024-06-14 06:53 UTC, loc-nguyenthien commented on src/chat/ChatScreen.tsx
> +    const curerntTime = Date.now();
```suggestion
    const currentTime = Date.now();
```

2024-06-14 06:53 UTC, loc-nguyenthien commented on src/chat/ChatScreen.tsx
> +            message.createdAt >= new Date(curerntTime)
```suggestion
            message.createdAt >= new Date(currentTime)
```

2024-06-14 07:31 UTC, huydosgtech commented on src/chat/ChatScreen.tsx
> +    const curerntTime = Date.now();
ok I changed it

2024-06-14 07:31 UTC, huydosgtech commented on src/chat/ChatScreen.tsx
> +            message.createdAt >= new Date(curerntTime)
I changed. Pls check again.

2024-06-19 14:57 UTC, baonguyenhsts approved these changes

2024-06-24 08:36 UTC, danhmaisgt approved these changes

2024-06-24 12:58 UTC, honghoangsts requested changes

2024-06-24 12:58 UTC, honghoangsts commented on src/chat/ChatScreen.tsx
> +    const currentTime = Date.now();
I think we need convert to UTC

2024-07-08 09:18 UTC, honghoangsts commented on src/services/firebase/firestore.ts
>        .onSnapshot((snapshot) => {
.where('createAt', '>', getCurrentTimestamp())
.onSnapshot(...)

2024-07-08 09:43 UTC, honghoangsts approved these changes

2024-07-08 09:44 UTC, merged