feat: [FC-9] show typing when input text
saigontechnology/rn-firebase-chat pull request #30
Opened 2024-06-17 08:51 UTC by huydosgtech

2024-06-17 08:52 UTC, huydosgtech commented
Image demo:

<img width="791" alt="Screenshot 2024-06-17 at 1 20 07 PM" src="https://github.com/saigontechnology/rn-firebase-chat/assets/105196859/ede12a15-5f13-4cff-ac3f-a389dc4256a8">

2024-06-17 09:20 UTC, loc-nguyenthien requested changes

2024-06-17 09:20 UTC, loc-nguyenthien commented on src/utilities/misc.ts
> +    .filter((userId) => userId !== currentUserId)
not need

2024-06-17 09:20 UTC, loc-nguyenthien commented on src/utilities/misc.ts
> +    .some((userId) => typingData[userId] === true);
```suggestion
    .some((userId) => userId !== currentUserId && typingData[userId] === true);
```

2024-06-17 10:10 UTC, huydosgtech commented on src/utilities/misc.ts
> +    .some((userId) => typingData[userId] === true);
ok I updated. Please check again. Thanks

2024-06-19 15:33 UTC, baonguyenhsts requested changes

2024-06-19 15:33 UTC, baonguyenhsts commented on src/hooks.ts
> +      if (enableTyping) {
from 59 - 72
```suggestion
     if (!enableTyping) return;

    if (newText.trim().length > 0) {
      clearTimeout(typingTimeoutRef.current);
      typingTimeoutRef.current = setTimeout(stopTyping, typingTimeoutSeconds);
      startTyping();
      return;
    }
    stopTyping();
```

2024-06-21 03:03 UTC, huydosgtech commented on src/hooks.ts
> +      if (enableTyping) {
ok I updated it

2024-06-21 03:03 UTC, huydosgtech commented on src/utilities/misc.ts
> +    .filter((userId) => userId !== currentUserId)
ok I resolved

2024-07-29 08:23 UTC, hoangSTS approved these changes

2024-07-30 06:51 UTC, huydosgtech commented
new UI
![Simulator Screenshot - iPhone 15 - 2024-07-30 at 13 29 35](https://github.com/user-attachments/assets/743c5515-d379-4951-b3e5-ab74ee2e42cb)

2024-07-31 02:58 UTC, danhmaisgt approved these changes

2024-07-31 03:00 UTC, loc-nguyenthien approved these changes

2024-08-02 02:18 UTC, merged