feat: [FC-10] custom bubble message
saigontechnology/rn-firebase-chat pull request #31
Opened 2024-06-19 09:03 UTC by huydosgtech

2024-06-19 09:06 UTC, huydosgtech commented on src/chat/ChatScreen.tsx
> +              <CustomBubble
this component come from [FC-5]

2024-06-24 08:46 UTC, danhmaisgt commented
Can you add a demo video or something please? It will be easy for me to understand your implementation.

2024-07-17 06:46 UTC, loc-nguyenthien requested changes

2024-07-17 06:46 UTC, loc-nguyenthien commented on src/chat/ChatScreen.tsx
> +  }, [firebaseInstance, partners]);
firebaseInstance is a ref, so we don't need it here

2024-07-24 04:34 UTC, loc-nguyenthien commented
Added video demo for chat status

https://github.com/user-attachments/assets/f83ab770-de0b-4cb7-b10c-0401c76c27a1

2024-07-26 07:02 UTC, loc-nguyenthien approved these changes

2024-07-26 07:02 UTC, loc-nguyenthien commented on src/services/firebase/firestore.ts
> +      console.log('Unread message ID updated successfully');
Remove log

2024-07-26 14:15 UTC, merged